Repository googleapis/java-storage-nio, pull requests merged in 2020-05, with the labels that each got.

#102 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: automerge, cla: yes, context: full

#103 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#109 chore: remove duplicate dependencies
  google-cloud-nio/pom.xml
Labels: cla: yes
