Repository googleapis/java-storage-nio, pull requests merged in 2020-12, with the labels that each got.

#283 chore: fix README generation
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: api: storage, cla: yes

#309 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#313 chore: regenerate common templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: storage, cla: yes, context: partial

#316 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#318 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#323 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#324 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#284 test: test that Java picks up the NIO provider
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/NIOTest.java
Labels: api: storage, cla: yes

#346 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full, merge
