Repository googleapis/java-storage-nio, pull requests merged in 2020-06, with the labels that each got.

#120 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#121 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#123 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#138 dep: update dependencies
  pom.xml
Labels: cla: yes

#135 test: update FakeStorageRpc to extend StorageRpcTestBase
  google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
Labels: cla: yes

#145 ci: re-generated to pick up changes from synthtool.
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#156 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-nio-examples/pom.xml
  google-cloud-nio-retrofit/pom.xml
  google-cloud-nio/pom.xml
  pom.xml
Labels: cla: yes
