Repository googleapis/java-storage-nio, pull requests merged in 2021-02, with the labels that each got.

#400 test: attempt tests up to 3 times
  google-cloud-nio/pom.xml
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageConfigurationTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileAttributeViewTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileAttributesTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageLateInitializationTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageOptionsTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStoragePathTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannelTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadFileChannelTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandlerTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageWriteChannelTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageWriteFileChannelTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/NIOTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/SeekableByteChannelPrefetcherTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/UnixPathTest.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: api: storage, cla: yes

#411 fix: cleanup use of non-preferred terms
  google-cloud-nio-retrofit/README.md
  google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageOption.java
  google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/LocalStorageHelper.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java
Labels: api: storage, automerge, cla: yes

#412 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#429 fix: use projectId from CloudStorageConfig
  google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageIsDirectoryTest.java
Labels: api: storage, automerge, cla: yes

#432 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#431 cleanup: buildcop -> flakybot
  .kokoro/build.sh
  synth.metadata
Labels: api: storage, cla: yes, context: none

#433 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#327 doc: Document CloudStoragePath
  google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java
Labels: api: storage, automerge, cla: yes

#434 chore: Re-generated to pick up changes from synthtool
  .github/workflows/auto-release.yaml
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  LICENSE
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#436 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#437 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#442 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#443 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#444 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#449 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#450 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#456 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#458 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#462 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#460 chore: add retries for build.sh for unit tests
  .kokoro/build.sh
  synth.py
Labels: api: storage, cla: yes

#464 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#470 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#471 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes
