Repository googleapis/java-storage-nio, pull requests merged in 2021-05, with the labels that each got.

#544 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: storage, cla: yes, context: none

#552 fix(test): update NIOTest to ensure LocalStorageHelper is used
  google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/NIOTest.java
Labels: api: storage, automerge, cla: yes

#554 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#555 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#545 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#559 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#560 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#561 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#563 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#564 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#566 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#572 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes

#573 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: storage, automerge, cla: yes
