Repository googleapis/java-storage-nio, pull requests merged in 2021-09, with the labels that each got.

#678 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: storage, automerge, context: full

#679 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, kokoro:force-run, api: storage, automerge, context: full

#684 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#686 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#689 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: storage, context: full

#690 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#692 build: remove reporting section in favor of the config from shared-config
  pom.xml
Labels: cla: yes, api: storage, automerge

#693 chore: Update CODEOWNERS for @googleapis/cloud-storage-dpe
  .github/CODEOWNERS
  .repo-metadata.json
Labels: cla: yes, api: storage, automerge

#697 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: storage, automerge

#717 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
Labels: cla: yes, api: storage

#730 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: storage, automerge

#731 chore(deps): Remove google-cloud-core (tests) dep version
  google-cloud-nio/pom.xml
Labels: cla: yes, api: storage
